# Generated by Django 4.0.6 on 2023-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('Message', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
